### ISSUE TITLE
can be add load more

### ISSUE THREAD

**Issue by sagar091** [GauravChaddha1996/CDSRecyclerView#1]
Hi,
I like CDSRecyclerView but there is only one feature load more not included. All 3 click-drag-swipe are usefull. Now just load more.. is remaining. so can u add this one in CDSRecyclewView? This is just my suggestion..

**Comment by GauravChaddha1996** [comment]
Hi sagar091. Thank you for starring my library. I'll try to add the load more feature in a few days. Though if you want or can, you can fork this and implement this and send me a pull request.

**Comment by sagar091** [comment]
@GauravChaddha1996 Yes, If I have much time then sure I'll do that. Thanks 👍

**Comment by GauravChaddha1996** [comment]
I have added this feature, alongside a bump in the minimum sdk version to 16. Also the API has changed a bit, I implemented the onBindViewHolder in a better way to give the custom view holder in the bindHolder() function, that one had to cast earlier in the onBindViewHolder(). Checkout the Readme for more.
