### ISSUE TITLE
Getting access to the holder

### ISSUE THREAD

**Issue by jej** [GauravChaddha1996/CDSRecyclerView#2]
Hi,
Thanks for your class, very handy to set up, even for beginner :)
I just wonder how I could get access to the holder of an item longpressed. I would like to change the color when an item is longpressed/dragged then change again when released. Currently, with the provided example, I just get the index position.
How can I get the holder object?
Thanks for your work and help,
J.

**Comment by GauravChaddha1996** [comment]
I believe recycler view has a function which returns the viewHolder for the given position like this : 
``` mRecyclerView.findViewHolderForAdapterPosition(position) ```
which returns the view holder for this position which you can cast back to your view holder and then use it.
I hope it solves your problem. I'm closing the issue, if you have any other issues, open them up.

**Comment by jej** [comment]
Thanks for your help. I tried to solve like this (event in class RecyclerViewAdapter.MyViewHolder), but it does not work very well:

>         public MyViewHolder(View itemView) {
>             super(itemView);
>             mTextView = (TextView) itemView.findViewById(R.id.item_recycler_view_text);
>             mTextView.setOnTouchListener(new View.OnTouchListener() {
>                 @Override
>                 public boolean onTouch(View v, MotionEvent event) {
>                     Log.d("CLICK", event.toString());
>                     switch(event.getAction()){
>                         case MotionEvent.ACTION_DOWN:
>                             v.setBackgroundColor(ContextCompat.getColor(v.getContext(), R.color.myColorAccent));
>                             break;
>                         case MotionEvent.ACTION_CANCEL:
>                         case MotionEvent.ACTION_UP:
>                             v.setBackgroundColor(ContextCompat.getColor(v.getContext(), R.myBackgroundColor));
>                             break;
>                     }
>                     return true;
>                 }
>             });
>         }

The color changes well, but as soon I move the item, ACTION_CANCEL event is fired and the highlight goes out... I guess there is a kind of conflict in the event catching... I think I will give up this idea!

**Comment by GauravChaddha1996** [comment]
The long press interface is intended for only returning which item was long pressed. I think if you want to highlight it you would have to do it yourself. I must confess that I've tried to do that feature as well but haven't found a good solution yet.

**Comment by jej** [comment]
Ok, so I can give up right now too :)) Thanks for your help.
