### ISSUE TITLE
ItemDragCompleteListener called for every position

### ISSUE THREAD

**Issue by PankajLPatil** [GauravChaddha1996/CDSRecyclerView#3]
Hi, I want to call an API after drag completion. But now ItemDragCompleteListener giving callback me after every changed position. How to deal with this? Please help.

**Comment by GauravChaddha1996** [comment]
Maybe you can debounce the API call (and cancel any previous call in flight) to wait for the drag to settle down. Currently the ItemDragCompleteListener is made in a way to report every drag position change.
